### ISSUE TITLE
Levenberg-Marquardt documentation example raises import error and crashes

### ISSUE THREAD

**Issue by rodrigoaraujo01** [itdxer/neupy#217]
I've tried to run the example shown on [1] and got the following output, followed by a Theanos error.

```
Main information

[ALGORITHM] LevenbergMarquardt

[OPTION] verbose = True
[OPTION] epoch_end_signal = None
[OPTION] show_epoch = 1
[OPTION] shuffle_data = False
[OPTION] train_end_signal = None
[OPTION] addons = None
[OPTION] error = mse
[OPTION] mu = 0.01
[OPTION] mu_update_factor = 1.2

[THEANO] Initializing Theano variables and functions.

You can find the C code in this temporary file: /var/folders/v9/r54fxj0s2g1g8g9x9lxclks40000gp/T/theano_compilation_error_uopz8746
Traceback (most recent call last):
  File "/Users/rodrigo/Documents/Doutorado/PET0305/lista_01/venv/lib/python3.7/site-packages/theano/scan_module/scan_perform_ext.py", line 48, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rodrigo/Documents/Doutorado/PET0305/lista_01/venv/lib/python3.7/site-packages/theano/scan_module/scan_perform_ext.py", line 63, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:
```

[1]: http://neupy.com/apidocs/neupy.algorithms.gd.lev_marq.html#neupy.algorithms.gd.lev_marq.LevenbergMarquardt

**Comment by itdxer** [comment]
It works on my machine. Can you share your library versions?

```python
In [1]: import numpy as np
   ...: from neupy import algorithms
   ...:
   ...: x_train = np.array([[1, 2], [3, 4]])
   ...: y_train = np.array([[1], [0]])
   ...:
   ...: lmnet = algorithms.LevenbergMarquardt((2, 3, 1))
   ...: lmnet.train(x_train, y_train)
   ...:
   ...:

In [2]: import theano;theano.__version__
Out[2]: '1.0.0'

In [3]: import neupy;neupy.__version__
Out[3]: '0.6.5'

In [4]: import platform;platform.python_version()
Out[4]: '3.6.0'
```

**Comment by rodrigoaraujo01** [comment]
Just tried it on my work machine, and it worked. I'm gonna check the library versions on my home machine later tonight and will update the post. Thanks for the quick reply.

**Comment by rodrigoaraujo01** [comment]
Just tested on my home computer, I have different versions than you do:

```
In [1]: import theano;theano.__version__
Out[1]: '1.0.0'

In [2]: import neupy;neupy.__version__
Out[2]: '0.6.4'

In [3]: import platform;platform.python_version()
Out[3]: '3.7.0'
```

**Comment by itdxer** [comment]
neupy 0.6.5 is a dev version, but it doesn't have any theano-related changes. I checked with 0.6.4 from pypi and everything works as well.

It looks like a theano bug with python 3.7, specifically with scan module

```python
import theano
import theano.tensor as T

k = T.iscalar("k")
A = T.vector("A")

# Symbolic description of the result
result, updates = theano.scan(fn=lambda prior_result, A: prior_result * A,
                              outputs_info=T.ones_like(A),
                              non_sequences=A,
                              n_steps=k)

# We only care about A**k, but scan has provided us with A**1 through A**k.
# Discard the values that we don't care about. Scan is smart enough to
# notice this and not waste memory saving them.
final_result = result[-1]

# compiled function that returns A**k
power = theano.function(inputs=[A,k], outputs=final_result, updates=updates)

print(power(range(10),2))
print(power(range(10),4))
```

from here: http://deeplearning.net/software/theano/library/scan.html

can you check if you have the same problem in python 3.7?

I have this problem with theano version 1.0.0 and 1.0.2

**Comment by itdxer** [comment]
NeuPy has been moved to tensorflow and I have to close this issue since it was related to the theano library which was completely removed starting from 0.7.0 version
