### ISSUE TITLE
How do you compile a network? (v0.7.0)

### ISSUE THREAD

**Issue by mlaradji** [itdxer/neupy#220]
## Issue

I have noticed that `LayerConnection.compile` exists in versions <0.7.0, but does not exist in v0.7.0. My question is, is there a function in neupy v0.7.0 for compiling a network?

## Extra information

Running the following code (adapted from http://neupy.com/docs/layers/basics.html#build-networks-from-the-code):
```
from neupy import layers

network = layers.join(
    layers.Input(10),
    layers.Relu(20),
    layers.Relu(4),
)

predict = network.initialize()

import numpy as np

# Convert matrix to float. Type of the
# float depends on theano.config.floatX variable
x_test = np.random.random((12, 10)).astype('float32')

y_predicted = network.predict(x_test)
```
results in the following error:
```
---------------------------------------------------------------------------
FailedPreconditionError                   Traceback (most recent call last)
~/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1291     try:
-> 1292       return fn(*args)
   1293     except errors.OpError as e:

~/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1276       return self._call_tf_sessionrun(
-> 1277           options, feed_dict, fetch_list, target_list, run_metadata)
   1278 

~/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1366         self._session, options, feed_dict, fetch_list, target_list,
-> 1367         run_metadata)
   1368 

FailedPreconditionError: Attempting to use uninitialized value layer/relu-27/weight
	 [[{{node layer/relu-27/weight/read}} = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](layer/relu-27/weight)]]

During handling of the above exception, another exception occurred:

FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-36-4ecd0640d4a1> in <module>
     14 x_test = np.random.random((12, 10)).astype('float32')
     15 
---> 16 y_predicted = network.predict(x_test)

~/.conda/envs/neupy/lib/python3.6/site-packages/neupy-0.7.0-py3.6.egg/neupy/layers/connections/base.py in predict(self, *args, **kwargs)
    137         """
    138         session = tensorflow_session()
--> 139         return session.run(self.output(*args, **kwargs))
    140 
    141 

~/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    885     try:
    886       result = self._run(None, fetches, feed_dict, options_ptr,
--> 887                          run_metadata_ptr)
    888       if run_metadata:
    889         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1108     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1109       results = self._do_run(handle, final_targets, final_fetches,
-> 1110                              feed_dict_tensor, options, run_metadata)
   1111     else:
   1112       results = []

~/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1284     if handle is None:
   1285       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1286                            run_metadata)
   1287     else:
   1288       return self._do_call(_prun_fn, handle, feeds, fetches)

~/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1306           self._config.experimental.client_handles_error_formatting):
   1307         message = error_interpolation.interpolate(message, self._graph)
-> 1308       raise type(e)(node_def, op, message)
   1309 
   1310   def _extend_graph(self):

FailedPreconditionError: Attempting to use uninitialized value layer/relu-27/weight
	 [[{{node layer/relu-27/weight/read}} = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](layer/relu-27/weight)]]

Caused by op 'layer/relu-27/weight/read', defined at:
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/asyncio/base_events.py", line 1434, in _run_once
    handle._run()
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-36-4ecd0640d4a1>", line 6, in <module>
    layers.Relu(4),
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/neupy-0.7.0-py3.6.egg/neupy/layers/connections/utils.py", line 41, in join
    merged_connections = reduce(LayerConnection, connections)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/neupy-0.7.0-py3.6.egg/neupy/layers/connections/base.py", line 396, in __init__
    self.full_graph.connect_layers(left.output_layers, right.input_layers)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/neupy-0.7.0-py3.6.egg/neupy/layers/connections/graph.py", line 378, in connect_layers
    next_layer.initialize()
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/neupy-0.7.0-py3.6.egg/neupy/layers/connections/base.py", line 54, in wrapper
    result = method(*args, **kwargs)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/neupy-0.7.0-py3.6.egg/neupy/layers/activations.py", line 55, in initialize
    super(ActivationLayer, self).initialize()
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/neupy-0.7.0-py3.6.egg/neupy/layers/base.py", line 252, in initialize
    shape=self.weight_shape, trainable=True)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/neupy-0.7.0-py3.6.egg/neupy/layers/base.py", line 176, in add_parameter
    parameter = create_shared_parameter(value, layer_name, shape)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/neupy-0.7.0-py3.6.egg/neupy/layers/base.py", line 70, in create_shared_parameter
    return tf.Variable(asfloat(value), name=name, dtype=tf.float32)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 145, in __call__
    return cls._variable_call(*args, **kwargs)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 141, in _variable_call
    aggregation=aggregation)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 120, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2441, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 147, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1104, in __init__
    constraint=constraint)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1266, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 81, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3354, in identity
    "Identity", input=input, name=name)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/mlaradji/.conda/envs/neupy/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value layer/relu-27/weight
	 [[{{node layer/relu-27/weight/read}} = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](layer/relu-27/weight)]]
```

The most probable source of this error is that I did not compile the model; indeed, the output of `network.compile()` is:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-37-8b1a6a8dba8c> in <module>
----> 1 network.compile()

AttributeError: 'LayerConnection' object has no attribute 'compile'
```

**Comment by mlaradji** [comment]
I should have looked further into it before posting this issue. The network can be compiled after an algorithm is defined, e.g.:
```
nnet = neupy.algorithms.RMSProp(
    network,

    batch_size=64,
    #step=step, #learning_rate
    #decay=,
    #
    error='categorical_crossentropy',
    shuffle_data=True,
)
```

Then, the prediction can be obtained via:
```
y_predicted = nnet.predict(x_test)
```

**Comment by itdxer** [comment]
Hi, yes, it was removed. The compilation stage was required for theano, but for tensorflow this step doesn't mean anything. I'll probably need to write small document that describes main differences.

Also, a few algorithms were removed, only because I've never used them in practice and I don't know anybody who did. These algorithms also didn't have advantage compare to the other algorithm available in the library.

The other thing is that the order of the image dimensions has changed in order to match the one that tensorflow uses , from `(batch, channel, height, width)` to `(batch, height, width, channel)` and it effected some layers, like `Convolution`. You can find working examples in the release/v0.7.0 branch
