### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by yaziciemre** [itdxer/neupy#226]
I tried to run mnist cnn sample, in examples folder.
But it gave the the following error

ValueError: negative dimensions are not allowed

Can you help me ?

**Comment by itdxer** [comment]
Hi @yaziciemre,

I just tested it and it works fine on my machine. Can you share your full exception log? Also, it will be nice if you can tell me your python, neupy and tensorflow versions.

**Comment by itdxer** [comment]
@yaziciemre and probably your numpy's version as well

**Comment by yaziciemre** [comment]
Thank you for the answer, 
The information that you asked is listed:

sys.version 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

tf.__version__ 1.6.0

numpy.__version__ 1.15.4

neupy.__version__ 0.6.4

Traceback (most recent call last):
  File "mn.py", line 86, in <module>
    reduction_freq=8,
  File "/usr/local/lib/python3.5/dist-packages/neupy/algorithms/gd/base.py", line 113, in __init__
    super(GradientDescent, self).__init__(connection, **options)
  File "/usr/local/lib/python3.5/dist-packages/neupy/algorithms/constructor.py", line 279, in __init__
    self.connection = clean_layers(connection)
  File "/usr/local/lib/python3.5/dist-packages/neupy/algorithms/constructor.py", line 89, in clean_layers
    connection = layers.join(*connection)
  File "/usr/local/lib/python3.5/dist-packages/neupy/layers/connections/utils.py", line 41, in join
    merged_connections = reduce(LayerConnection, connections)
  File "/usr/local/lib/python3.5/dist-packages/neupy/layers/connections/base.py", line 404, in __init__
    self.full_graph.connect_layers(left.output_layers, right.input_layers)
  File "/usr/local/lib/python3.5/dist-packages/neupy/layers/connections/graph.py", line 375, in connect_layers
    next_layer.initialize()
  File "/usr/local/lib/python3.5/dist-packages/neupy/layers/activations.py", line 54, in initialize
    super(ActivationLayer, self).initialize()
  File "/usr/local/lib/python3.5/dist-packages/neupy/layers/base.py", line 231, in initialize
    shape=self.weight_shape, trainable=True)
  File "/usr/local/lib/python3.5/dist-packages/neupy/layers/base.py", line 160, in add_parameter
    parameter = create_shared_parameter(value, theano_name, shape)
  File "/usr/local/lib/python3.5/dist-packages/neupy/layers/base.py", line 68, in create_shared_parameter
    value = value.sample(shape)
  File "/usr/local/lib/python3.5/dist-packages/neupy/init.py", line 324, in sample
    return np.random.normal(loc=0, scale=std, size=shape)
  File "mtrand.pyx", line 1652, in mtrand.RandomState.normal
  File "mtrand.pyx", line 242, in mtrand.cont2_array_sc
ValueError: negative dimensions are not allowed

**Comment by itdxer** [comment]
Ah, I see what's the problem. When neupy was moved to tensorflow, the API changed a bit and it won't work for older versions. The position of the channel had changed and before input was specified as `Input((1, 28, 28))` (channel first) and now it's specified as `Input((28, 28, 1))` (channel last)

You have two options:
1. (better option) Upgrade neupy to the latest version that uses tensorflow as a backend and use current example
2. Go to the 0.6.4 branch and use example from it for the older version (<= 0.6.5): https://github.com/itdxer/neupy/blob/v0.6.4/examples/cnn/mnist_cnn.py

I hope it helps

**Comment by itdxer** [comment]
Also, in case if you want to upgrade to the newer version (0.7.2 latest at the moment) than it's better to install tensorflow using conda. https://towardsdatascience.com/stop-installing-tensorflow-using-pip-for-performance-sake-5854f9d9eb0c
