### ISSUE TITLE
Questions about the Quasi-Newton Method Implemented in Neupy

### ISSUE THREAD

**Issue by bright1993ff66** [itdxer/neupy#263]
Hi, I am checking the [Quasi-Newton method](http://neupy.com/apidocs/neupy.algorithms.gd.quasi_newton.html) in Neupy. But after running the codes posted in your tutorial page:

```Python
import numpy as np
from neupy import algorithms
from neupy.layers import *

x_train = np.array([[1, 2], [3, 4]])
y_train = np.array([[1], [0]])

optimizer = algorithms.QuasiNewton(
    Input(2) >> Sigmoid(3) >> Sigmoid(1),
    update_function='bfgs'
)
optimizer.train(x_train, y_train, epochs=10)
```
I get the following errors:

```bash
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
c:\program files\python 3.5\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

c:\program files\python 3.5\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

c:\program files\python 3.5\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InvalidArgumentError: You must feed a value for placeholder tensor 'placeholder/input/input-1' with dtype float and shape [?,28,28,1]
	 [[{{node placeholder/input/input-1}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-6-2211063aa2a2> in <module>
      8 optimizer = algorithms.QuasiNewton(
      9     Input(2) >> Sigmoid(3) >> Sigmoid(1),
---> 10     update_function='bfgs'
     11 )
     12 optimizer.train(x_train, y_train, epochs=10)

c:\program files\python 3.5\lib\site-packages\neupy\algorithms\gd\base.py in __init__(self, network, options, **kwargs)
    147         self.functions = AttributeKeyDict()
    148         self.network.outputs
--> 149         self.init_functions()
    150 
    151         self.logs.message(

c:\program files\python 3.5\lib\site-packages\neupy\algorithms\gd\base.py in init_functions(self)
    177                 training_updates.extend(update_ops)
    178 
--> 179         tf_utils.initialize_uninitialized_variables()
    180 
    181         with tf.name_scope('optimizer'):

c:\program files\python 3.5\lib\site-packages\neupy\utils\tf_utils.py in initialize_uninitialized_variables(variables)
    111 
    112     if len(not_initialized_vars):
--> 113         session.run(tf.variables_initializer(not_initialized_vars))
    114 
    115 

c:\program files\python 3.5\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

c:\program files\python 3.5\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

c:\program files\python 3.5\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

c:\program files\python 3.5\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: You must feed a value for placeholder tensor 'placeholder/input/input-1' with dtype float and shape [?,28,28,1]
	 [[node placeholder/input/input-1 (defined at c:\program files\python 3.5\lib\site-packages\neupy\layers\graph.py:208) ]]

Caused by op 'placeholder/input/input-1', defined at:
  File "c:\program files\python 3.5\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python 3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files\python 3.5\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\program files\python 3.5\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\program files\python 3.5\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "c:\program files\python 3.5\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "c:\program files\python 3.5\lib\asyncio\base_events.py", line 301, in run_forever
    self._run_once()
  File "c:\program files\python 3.5\lib\asyncio\base_events.py", line 1198, in _run_once
    handle._run()
  File "c:\program files\python 3.5\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "c:\program files\python 3.5\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "c:\program files\python 3.5\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\program files\python 3.5\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "c:\program files\python 3.5\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "c:\program files\python 3.5\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "c:\program files\python 3.5\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "c:\program files\python 3.5\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "c:\program files\python 3.5\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "c:\program files\python 3.5\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "c:\program files\python 3.5\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "c:\program files\python 3.5\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\program files\python 3.5\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\program files\python 3.5\lib\site-packages\IPython\core\interactiveshell.py", line 2817, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "c:\program files\python 3.5\lib\site-packages\IPython\core\interactiveshell.py", line 2843, in _run_cell
    return runner(coro)
  File "c:\program files\python 3.5\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "c:\program files\python 3.5\lib\site-packages\IPython\core\interactiveshell.py", line 3018, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\program files\python 3.5\lib\site-packages\IPython\core\interactiveshell.py", line 3183, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "c:\program files\python 3.5\lib\site-packages\IPython\core\interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-18079bee0efa>", line 43, in <module>
    shuffle_data=True,
  File "c:\program files\python 3.5\lib\site-packages\neupy\algorithms\gd\base.py", line 148, in __init__
    self.network.outputs
  File "c:\program files\python 3.5\lib\site-packages\neupy\layers\graph.py", line 168, in wrapper
    setattr(self, attr, function(self))
  File "c:\program files\python 3.5\lib\site-packages\neupy\layers\graph.py", line 230, in outputs
    networks_output = self.output(*as_tuple(self.inputs))
  File "c:\program files\python 3.5\lib\site-packages\neupy\layers\graph.py", line 168, in wrapper
    setattr(self, attr, function(self))
  File "c:\program files\python 3.5\lib\site-packages\neupy\layers\graph.py", line 208, in inputs
    name="placeholder/input/{}".format(layer.name),
  File "c:\program files\python 3.5\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2077, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "c:\program files\python 3.5\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5790, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "c:\program files\python 3.5\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "c:\program files\python 3.5\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "c:\program files\python 3.5\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "c:\program files\python 3.5\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'placeholder/input/input-1' with dtype float and shape [?,28,28,1]
	 [[node placeholder/input/input-1 (defined at c:\program files\python 3.5\lib\site-packages\neupy\layers\graph.py:208) ]]

```
I think there is something wrong with the tensorflow backend. The data has not been fed to the placeholder. Any help would be appreciated!

**Comment by itdxer** [comment]
Hi, thank you for reporting this problem.

I can see that you're using python 3.5. The same example works for me in the environment with the following neap and Tensorflow versions. Can you tell me what versions do you use?

```
In [3]: import neupy; print(neupy.__version__)
0.8.2

In [4]: import tensorflow; print(tensorflow.__version__)
1.13.1

In [6]: import platform; print(platform.python_version())
3.7.3
```

**Comment by itdxer** [comment]
I've removed support for the python 3.5 version since it's quite time consuming to maintain a lot of python versions from one project maintainer. I'm not sure if it's possible to you to upgrade to python 3.6

**Comment by itdxer** [comment]
@bright1993ff66 did you manage to solve your problem?

**Comment by bright1993ff66** [comment]
Thank you very much for your answers! I have updated to Python 3.6 and now the codes work. @itdxer
