### ISSUE TITLE
RuntimeError: generator didn't stop after throw()

### ISSUE THREAD

**Issue by itdxer** [itdxer/neupy#71]
Keyboard interruption during the NN training cause the following error

```
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_classifier.py", line 80, in <module>
    classifier.train(x_train, y_train, x_test, y_test, epochs=100)
  File "/Users/projects/neupy/neupy/network/constructor.py", line 451, in train
    *args, **kwargs
  File "/Users/projects/neupy/neupy/network/learning.py", line 43, in train
    epochs=epochs, epsilon=epsilon
  File "/Users/projects/neupy/neupy/network/base.py", line 485, in train
    epoch_summary.close()
  File "/Users/itdxer/.pyenv/versions/3.4.3/lib/python3.4/contextlib.py", line 78, in __exit__
    raise RuntimeError("generator didn't stop after throw()")
RuntimeError: generator didn't stop after throw()
```

**Comment by itdxer** [comment]
release/v0.2.0rc1
