### ISSUE TITLE
Password recovery example - Errors

### ISSUE THREAD

**Issue by markusdanek** [itdxer/neupy#95]
Hi, 

I just wanted to test the password recovery example but when I try to call it (`python password_recovery.py`) I get those errors:

```
Traceback (most recent call last):
  File "password_recovery.py", line 11, in <module>
    from neupy import algorithms
  File "/usr/local/lib/python2.7/site-packages/neupy/algorithms/__init__.py", line 1, in <module>
    from .gd.base import *
  File "/usr/local/lib/python2.7/site-packages/neupy/algorithms/gd/base.py", line 11, in <module>
    from neupy.network import ConstructableNetwork
  File "/usr/local/lib/python2.7/site-packages/neupy/network/__init__.py", line 3, in <module>
    from .constructor import ConstructableNetwork, ConstructableNetwork
  File "/usr/local/lib/python2.7/site-packages/neupy/network/constructor.py", line 5, in <module>
    import theano.sparse
  File "/usr/local/lib/python2.7/site-packages/theano/sparse/__init__.py", line 19, in <module>
    from theano.sparse.basic import *
  File "/usr/local/lib/python2.7/site-packages/theano/sparse/basic.py", line 25, in <module>
    import theano.tests.unittest_tools as utt
  File "/usr/local/lib/python2.7/site-packages/theano/tests/unittest_tools.py", line 7, in <module>
    from nose_parameterized import parameterized
ImportError: No module named nose_parameterized
```

**Comment by itdxer** [comment]
Hello,

This looks like a Theano v0.8.2 issue. Try to install the node-parameterized library

```bash
$ pip install nose-parameterized==0.5.0
```

It's odd that NeuPy didn't install it. https://github.com/itdxer/neupy/blob/master/requirements/main.txt#L8

**Comment by itdxer** [comment]
I've updated pip package (version 0.2.2), so you can re-install the package.

**Comment by itdxer** [comment]
@markusdanek: Did you solve your problem?

**Comment by markusdanek** [comment]
Yes! Thank you 👍
